/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Ubli - Acessibilidade urbana
 */
import type { PontoAcessibilidadeDTO } from './pontoAcessibilidadeDTO';

export type CadastraPontoAcessibilidadeBody = {
  ponto_acessibilidade: PontoAcessibilidadeDTO;
  fotos_local: Blob[];
};
