services:
  mysql:
    image: 'mysql:8.0'
    restart: unless-stopped
    environment:
      - 'MYSQL_DATABASE=ubli'
      - 'MYSQL_PASSWORD=ubli_database'
      - 'MYSQL_ROOT_PASSWORD=ubli_admin'
      - 'MYSQL_USER=ubli'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
